"use strict";

const { field, enabled, connection, connectionChecks } = require("./fields");
const { outgoing } = require("./outgoing");
const { ARG_TYPES, isSendable } = require("../osc-args");

/**
 * What one tile can send.
 *
 * Clip selection is an index or a name, which is how Resolume, Millumin,
 * QLab and Ableton all address a cue. "bool" and "no argument" are dropped
 * from the list because they carry no identity: every tile would send the
 * identical message and the grid would be a row of buttons wearing pictures.
 */
const ITEM_ARG_TYPES = ARG_TYPES.filter(function (type) {
  return type.id !== "bool" && type.id !== "none";
});

const ITEM_CLASS = "oscar-media-item";
const THUMB_CLASS = "oscar-media-thumb";
const LABEL_CLASS = "oscar-media-label";
const SELECTED_CLASS = "oscar-selected";

const DEFAULT_ITEMS = "Clip 1|1; Clip 2|2; Clip 3|3";

/**
 * Split one configured line into a tile.
 *
 * The format is `label`, `label|value` or `label|value|image`.
 *
 * Items are separated by a semicolon OR a newline, and that is a concession to
 * the settings panel rather than a preference: a trait is a single-line text
 * input, so a newline cannot be typed into one. Semicolons are what a person
 * can actually enter; newlines are accepted as well so a project file edited by
 * hand, or generated by a script, reads the way a list should.
 *
 * The cost is that a label cannot itself contain `;` or `|`. That is the price
 * of staying inside the four trait types OSCAR has, and it buys a designer the
 * ability to set up a twenty-clip gallery without a new kind of settings UI.
 */
function parseItems(raw) {
  const text = String(raw == null ? "" : raw);

  return text
    .split(/[\n;]/)
    .map(function (line) {
      return line.trim();
    })
    .filter(Boolean)
    .filter(function (line) {
      // A line with neither a label nor a picture would draw an empty square
      // that sends something when tapped -- a trap, not a tile. A picture with
      // no label is fine, and is what a gallery of stills usually wants.
      const parts = line.split("|");
      return (parts[0] || "").trim() !== "" || (parts[2] || "").trim() !== "";
    })
    .map(function (line, index) {
      const parts = line.split("|").map(function (part) {
        return part.trim();
      });
      return {
        label: parts[0],
        // No value given means the tile sends its own position. A clip grid is
        // almost always addressed by index, so the common case is the one that
        // needs the least typing.
        value: parts.length > 1 && parts[1] !== "" ? parts[1] : String(index + 1),
        image: parts.length > 2 ? parts[2] : "",
      };
    });
}

/**
 * OSC media browser: a grid of thumbnails, one tap picks one.
 *
 * The need it answers is an operator on a tablet choosing which video plays in
 * a room -- browsing pictures rather than remembering that the calming forest
 * loop is clip 7. Picking a tile sends its value, which is exactly the message
 * a clip-launching program already listens for.
 *
 * It is a chooser, not a media library: it displays images the designer points
 * it at and it sends a selection. It does not upload, store, transcode or
 * preview video.
 */
const media = {
  name: "oscar-media",
  tag: "div",
  attributes: { class: "oscar-media" },

  block: {
    label: "Media Browser",
    category: "OSC",
    icon:
      '<svg viewBox="0 0 24 24" width="48" height="48"><path fill="currentColor" ' +
      'd="M4,4H10V10H4V4M14,4H20V10H14V4M4,14H10V20H4V14M14,14H20V20H14V14M16,16V18H18V16H16Z"/></svg>',
  },

  defaults: {
    enabled: true,
    ip: "localhost",
    port: 7000,
    message: "/clip",
    items: DEFAULT_ITEMS,
    columns: 3,
    showLabels: true,
    // 1-based, matching what an item with no explicit value sends. 0 is
    // "nothing picked yet", which is the honest state of a surface that has
    // just been laid out.
    selected: 0,
    argType: "i",
  },

  fields: [enabled()].concat(connection()).concat([
    field("items", "Items", "text", {
      placeholder: "Intro|1; Waves|2|images/waves.png",
    }),
    field("columns", "Columns", "number", { min: 1, max: 12, step: 1 }),
    field("showLabels", "Show labels", "checkbox"),
    field("selected", "Selected", "number", { min: 0, step: 1 }),
    field("argType", "Argument type", "select", { options: ITEM_ARG_TYPES }),
  ]),

  checks: Object.assign({}, connectionChecks(), {
    items: checkItems,
    columns: checkColumns,
    selected: checkSelected,
  }),

  attach: function (el, ctx) {
    // Everything this widget put in the element, so it can take exactly that
    // back out again and never touch anything it did not create.
    let tiles = [];
    let items = [];

    // The element's own document, not a global one: the canvas is an iframe,
    // and a node built by the outer document belongs to the wrong tree.
    const doc = el.ownerDocument;

    build();

    /** Draw the grid the settings describe. */
    function build() {
      clear();
      if (!doc) return;

      items = parseItems(ctx.get("items"));

      const columns = Math.max(1, Math.round(Number(ctx.get("columns")) || 1));
      // Written straight onto the element rather than left to a CSS variable,
      // so the layout holds up in engines that will not substitute a variable
      // inside repeat().
      el.style.setProperty("grid-template-columns", "repeat(" + columns + ", 1fr)");

      const withLabels = ctx.get("showLabels") !== false;

      items.forEach(function (item, index) {
        const tile = doc.createElement("div");
        tile.classList.add(ITEM_CLASS);

        if (item.image) {
          const thumb = doc.createElement("img");
          thumb.classList.add(THUMB_CLASS);
          // setAttribute, not innerHTML: the label and the URL are typed by a
          // person into a settings field, and building markup out of them
          // would make that field a way to inject script into the surface.
          thumb.setAttribute("src", item.image);
          // The label is already on screen, so an alt repeating it is noise to
          // a screen reader.
          thumb.setAttribute("alt", "");
          tile.appendChild(thumb);
        }

        if (withLabels) {
          const label = doc.createElement("span");
          label.classList.add(LABEL_CLASS);
          label.textContent = item.label;
          tile.appendChild(label);
        }

        // Click rather than pointerdown: a finger dragging the grid to scroll
        // it must not pick whatever it started on, and only click distinguishes
        // the two. There is nothing to be gained from firing early here -- this
        // picks a clip, it is not a drum pad.
        const onClick = function () {
          pick(index);
        };
        tile.addEventListener("click", onClick);

        tiles.push(tile);
        // Kept next to the element so detach removes the listener it added,
        // not one it guessed at.
        tile.oscarOnClick = onClick;
        el.appendChild(tile);
      });

      paintSelection();
    }

    function clear() {
      tiles.forEach(function (tile) {
        if (tile.oscarOnClick) tile.removeEventListener("click", tile.oscarOnClick);
        // Guarded: a re-render can have emptied the element underneath us, and
        // removing a node that is no longer a child throws.
        if (tile.parentNode === el) el.removeChild(tile);
      });
      tiles = [];
    }

    /** Show which tile is the current choice. */
    function paintSelection() {
      const selected = Number(ctx.get("selected"));
      tiles.forEach(function (tile, index) {
        if (index + 1 === selected) tile.classList.add(SELECTED_CLASS);
        else tile.classList.remove(SELECTED_CLASS);
      });
    }

    /**
     * Choose a tile.
     *
     * Picking the tile that is already picked still sends. Re-selecting a clip
     * is a real instruction -- it restarts it -- and swallowing the second tap
     * would make the grid feel broken to anyone trying exactly that.
     */
    function pick(index) {
      const item = items[index];
      if (!item) return;

      // Silent: this is the widget recording what the hand did, not a settings
      // edit, and a re-validate mid-show is the last thing anyone needs.
      ctx.set("selected", index + 1);
      paintSelection();

      ctx.send(
        outgoing(
          {
            enabled: ctx.get("enabled"),
            ip: ctx.get("ip"),
            port: ctx.get("port"),
            message: ctx.get("message"),
            argType: ctx.get("argType"),
          },
          item.value
        )
      );
    }

    const stopBuild = ctx.onChange(["items", "columns", "showLabels"], build);
    // Separate from the rebuild: setting the selection in the panel should move
    // a highlight, not tear down and re-create every thumbnail, which would
    // make every image flash as it reloads.
    const stopPaint = ctx.onChange(["selected"], paintSelection);

    return function detach() {
      clear();
      if (stopBuild) stopBuild();
      if (stopPaint) stopPaint();
    };
  },
};

function checkItems(value, config) {
  const text = String(value == null ? "" : value).trim();
  // An empty gallery is a work in progress, not a mistake.
  if (!text) return null;

  const items = parseItems(text);
  if (!items.length) return "List the items like: Intro|1; Waves|2";

  const argType = (config && config.argType) || "i";
  for (const item of items) {
    if (isSendable(argType, item.value)) continue;
    // Caught here because the alternative is a tile that looks fine and does
    // nothing: the send path drops an unsendable value rather than guessing.
    return (
      'Item "' + item.label + '" would send "' + item.value + '", which cannot be sent as ' + argType
    );
  }
  return null;
}

function checkColumns(value) {
  const columns = Number(value);
  if (Number.isInteger(columns) && columns >= 1 && columns <= 12) return null;
  return "Columns has to be a whole number between 1 and 12";
}

function checkSelected(value) {
  const selected = Number(value);
  if (Number.isInteger(selected) && selected >= 0) return null;
  return "Selected is the position of an item, or 0 for none";
}

module.exports = {
  media,
  parseItems,
  ITEM_ARG_TYPES,
  ITEM_CLASS,
  THUMB_CLASS,
  LABEL_CLASS,
  SELECTED_CLASS,
  DEFAULT_ITEMS,
};
